name: py35
dependencies:
- pip=8.1.2=py35_0
- python=3.5.1=0
- setuptools=20.3=py35_0
- pip:
  - parsley
  - cryptography
  - paramiko
  - numpy
  - scipy
  - pywavelets
  - lmfit
  - jupyter_client
  - nbsphinx
  - releases